const express = require("express");
const router = express.Router();
const Booking = require("../Models/Booking");
const nodemailer= require("nodemailer");

router.post("/create", async (req, res) => {
    try {
        const { customerId, hostId, listingId, startDate, endDate, totalPrice, customerEmail } = req.body;

        // Create a new booking instance
        const newBooking = new Booking({
            customerId,
            hostId,
            listingId,
            startDate,
            endDate,
            totalPrice,
            customerEmail
        });

        // Save the new booking to the database
        await newBooking.save();
        let transporter=nodemailer.createTransport({
            service:'gmail',
            auth:{
                user:'dhruvparmar2204@gmail.com',
                pass: 'jelw wmrs scvx hsrc'
        
            }
        })
        let mailOption={
            from:'"Dhruv parmar"<dhruvparmar2204@gmail.com>',
            to:customerEmail,
            subject:'Autogenrated Email',
            text:'Hello, this is an autogenerated email using nodemailer in Node.js!',
            html: '<b>Hello, this is an autogenerated email using nodemailer in Node.js!</b>' // HTML body

        }
        transporter.sendMail(mailOption,(error,info)=>{
            if(error)
            {
                return console.log("there is an error",error)

            }
            console.log('Message sent',info.messageId)
            console.log('privew URL',nodemailer.getTestMessageUrl)
        })
        res.status(200).json({ message: "Your booking has been done", booking: newBooking });
    } catch (error) {
        console.error("There is something wrong:", error.message);
        res.status(400).json({ message: "There is something wrong, unable to book now" });
    }
});
router.get('/get',async(req,res)=>{
    try {
        const Bookings=await Booking.find()
        res.status(200).json({booking:Bookings})
        
    } catch (error) {
        console.log("not found ",error.message)
        res.status(400).json({message:"error something  as, dasm dwrong"})
        
    }
})


module.exports = router;
